name: CD On Tag

on:
  push:
    tags:
      - "v*"

env:
  SOLUTION_PATH: "src/StackNucleus.sln"
  NUGET_SRC_URL: "https://api.nuget.org/v3/index.json"
  NUGET_DIR: "nupkg"

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release /p:TreatWarningsAsErrors=true

      - name: Check .NET and NuGet versions
        run: |
          dotnet --version
          dotnet nuget --version

      - name: Prepare NuGet output directory
        if: ${{ steps.newtag.outputs.tag != '' }}
        run: mkdir -p ${{ env.NUGET_DIR }}

      - name: Pack
        if: ${{ steps.newtag.outputs.tag != '' }}
        run: dotnet pack ${{ env.SOLUTION_PATH }} --no-restore --configuration Release -o ${{ env.NUGET_DIR }}

      - name: Publish to NuGet.org
        if: ${{ steps.newtag.outputs.tag != '' }}
        run: |
          dotnet nuget push ${{ env.NUGET_DIR }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SRC_URL }} --skip-duplicate
